import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const kumbhSans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "PRODHOT | Elevated Quality",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>
        <Header />
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
